table fact_Achievement
	lineageTag: f09cc7d6-1423-4854-ae90-270ae535198f

	column Achievement_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 42affd34-4066-448b-94e9-b5c1571ce057
		summarizeBy: none
		sourceColumn: Achievement_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Points
		dataType: int64
		formatString: 0
		lineageTag: 0102f8a7-c1b7-431a-9f04-85c132681136
		summarizeBy: sum
		sourceColumn: Points

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: b49ed129-090a-4bbf-8393-39b57a4b23d8
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column studentkey
		dataType: string
		lineageTag: 8b923e1b-679b-463d-bc30-1b332ab2ea1b
		summarizeBy: none
		sourceColumn: studentkey

		annotation SummarizationSetBy = Automatic

	column Academic_Year
		dataType: string
		lineageTag: 61c426d4-e6c5-4584-857c-9c736701b86b
		summarizeBy: none
		sourceColumn: Academic_Year

		annotation SummarizationSetBy = Automatic

	column studentacademicyeargroupkey
		dataType: int64
		formatString: 0
		lineageTag: b7ee6c9e-0557-4019-9ecf-38145d84b2f4
		summarizeBy: none
		sourceColumn: studentacademicyeargroupkey

		annotation SummarizationSetBy = Automatic

	partition fact_Achievement = m
		mode: import
		queryGroup: Data
		source = ```
				let
				    // Directly use Path_DataModel to locate the table
				    Path = Path_DataModel,
				    
				    // Combine the path with the table name
				    CombinedURL = Path & "/fact_Achievement",
				    
				    // Load Data from the Data Lake
				    Data = AzureStorage.DataLake(CombinedURL),
				    
				    // Filter for Parquet files and convert
				    FilteredFiles = Table.SelectRows(Data, each [Extension] = ".parquet"),
				    ConvertedData = Table.TransformColumns(FilteredFiles, {"Content", Parquet.Document}, null),
				    
				    // Combine all files into one table
				    CombinedData = Table.Combine(ConvertedData[Content])
				in
				    CombinedData
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

